pipeline {
  agent { label 'ubuntu-slave-vps1' }
  environment {
    DOCKER_REGISTRY_NAME        = credentials('DOCKER_REGISTRY_NAME')
    DOCKER_REGISTRY_USERNAME    = credentials('DOCKER_REGISTRY_USERNAME')
    DOCKER_REGISTRY_PASSWORD    = credentials('DOCKER_REGISTRY_PASSWORD')
  }
  stages {

    stage ('Integration Code') {
      parallel {
        stage ('Code Quality') {
          stages {
            stage('Code Quality Check') {
              agent {
                docker {
                  image 'gradle:jdk8-alpine'
                  label 'ubuntu-slave-vps1'
                }
              }

              steps {
                script{
                  def scannerHome = tool 'sonar_scanner';
                  withSonarQubeEnv('sonar') {
                      sh "${scannerHome}/bin/sonar-scanner \
                          -Dsonar.projectKey=color-app \
                          -Dsonar.projectName=color-app \
                          -Dsonar.host.url=${SONAR_HOST_URL}"
                  }
                }
              }
            }
            stage("Quality gate") {
              steps {
                waitForQualityGate abortPipeline: true
              }
            }
          }
        }

        stage ('Code Testing') {
          stages {
            stage ('Install Dependencies') {
              tools {
                nodejs 'nodejs 8.9.4'
              }
              steps {
                sh '''
                  echo "Installing..."
                  npm install
                  echo "Install dependencies successfully."
                  ls -al
                '''
              }
            }
            stage ('Test') {
              tools {
                nodejs 'nodejs 8.9.4'
              }
              steps {
                sh 'echo "Run unit test..."'
                sh 'npm test'
                sh 'echo "Run unit test successfully."'
                sh 'ls -al'
              }
            }
          }
        }
      }
    }

    stage ('Build') {
      when {
        anyOf {
            branch 'develop'
            branch 'release'
            tag pattern: "^v(\\d+(?:\\.\\d+)*)\$", comparator: "REGEXP"
        }
      }
      steps {
        nodejs(nodeJSInstallationName: 'nodejs 8.9.4') {
          sh 'echo "Build application..."'
          sh 'npm run build'
          sh 'echo "Build application successfully."'
          sh 'ls -al'
        }
        script {
          stash includes: 'build/', name: 'build'
        }
      }
    }

    stage ('Create and run docker images dev') {
      agent { label 'ubuntu-slave-vps1' }
      when {
        branch 'develop'
      }
      steps {
        script {
          unstash 'build'
        }
        sh '''
          ls -al
          echo "Starting to build docker image for dev env"
          docker build -t "${DOCKER_REGISTRY_NAME}/pick-color:dev-${BUILD_NUMBER}" -f docker/Dockerfile.no_build .
        '''
        // Push image to hub.docker.com
        sh '''
          echo ${DOCKER_REGISTRY_PASSWORD} | docker login -u ${DOCKER_REGISTRY_USERNAME} --password-stdin  
          docker push "${DOCKER_REGISTRY_NAME}/pick-color:develop-${BUILD_NUMBER}"
        '''
      }

      steps {
        sh '''
          docker stop color-app-dev || true && docker rm color-app-dev || true
          docker run -p 30080:80 --restart always -d --name color-app-dev ${DOCKER_REGISTRY_NAME}/pick-color:develop-${BUILD_NUMBER} 
        '''
      }
    }

    stage ('Create and run docker images stg') {
      agent { label 'ubuntu-slave-vps1' }
      when {
        branch 'release'
      }
      steps {
        script {
          unstash 'build'
        }
        sh '''
          ls -al
          echo "Starting to build docker image for dev env"
          docker build -t "${DOCKER_REGISTRY_NAME}/pick-color:dev-${BUILD_NUMBER}" -f docker/Dockerfile.no_build .
        '''
        // Push image to hub.docker.com
        sh '''
          echo ${DOCKER_REGISTRY_PASSWORD} | docker login -u ${DOCKER_REGISTRY_USERNAME} --password-stdin  
          docker push "${DOCKER_REGISTRY_NAME}/pick-color:stg-${BUILD_NUMBER}"
        '''
      }

      steps {
        sh '''
          docker stop color-app-dev || true && docker rm color-app-dev || true
          docker run -p 30090:80 --restart always -d --name color-app-dev ${DOCKER_REGISTRY_NAME}/pick-color:stg-${BUILD_NUMBER} 
        '''
      }
    }

    stage ('Create and run docker images prd') {
      agent { label 'ubuntu-slave-vps1' }
      when {
        tag pattern: "^v(\\d+(?:\\.\\d+)*)\$", comparator: "REGEXP"
      }
      input {
        message "Enter production version..."
        ok "Done"
        parameters {
          string(name: "IMAGE_TAG", defaultValue: "v0.0.0")
        }
      }
      steps {
        script {
          unstash 'build'
        }
        sh '''
          ls -al
          echo "Starting to build docker image, prepare for release"
          docker build -t "${DOCKER_REGISTRY_NAME}/pick-color:${IMAGE_TAG}" -f docker/Dockerfile.no_build .
        '''
        // Push image to hub.docker.com
        sh '''
          echo ${DOCKER_REGISTRY_PASSWORD} | docker login -u ${DOCKER_REGISTRY_USERNAME} --password-stdin  
          docker push "${DOCKER_REGISTRY_NAME}/pick-color:${IMAGE_TAG}"
        '''
      }

      steps {
        sh '''
          docker stop color-app-dev || true && docker rm color-app-dev || true
          docker run -p 30100:80 --restart always -d --name color-app-dev ${DOCKER_REGISTRY_NAME}/pick-color:${IMAGE_TAG}" 
        '''
      }
    }
  }
}